tug-cps/GameOpSysReactApp

- package-lock.json
- package.json
- public/locales/de/translation.json
- public/locales/en/translation.json
- src/App.tsx
- src/Consumers.tsx
- src/Home.tsx
- src/Login.tsx
- src/Routes.tsx
- src/Survey.tsx
- src/Verify.tsx
- src/common/PrivateRoute.tsx
- src/i18n.tsx
- src/index.tsx
* Add i18next as dependency
* Move content from `App` to `Home`
* Fix routing
> Issue-06: Add support for i18n

- package.json
- src/Routes.tsx
- src/index.tsx
> Issue-28: Fix routing on github

- public/locales/en/translation.json
- src/Achievement.tsx
- src/Home.tsx
- src/Routes.tsx
> #16 Add empty achievement page

- src/App.tsx
- src/Behavior.jsx
- src/Consumers.tsx
- src/Home.tsx
- src/Power.tsx
- src/Upload.tsx
- src/common/SimpleBottomNavigation.tsx
- src/locales/de/translation.json
- src/locales/en/translation.json
> Issue-44: Translate upload page

- src/Behavior.jsx
- src/Consumers.tsx
- src/Verify.tsx
- src/index.css
- src/locales/de/translation.json
- src/locales/en/translation.json
- src/service/BackendService.ts
- src/service/FakeBackend.ts
> Issue-20: Add remove option to consumers

- package-lock.json
- package.json
- src/Consumers.tsx
- src/service/BackendService.ts
- src/service/FakeBackend.ts
> Issue-19: Add add option to consumers

- src/Home.tsx
- src/User.tsx
- src/common/ConsumerTools.tsx
- src/common/DefaultAppBar.tsx
- src/common/DefaultBottomNavigation.tsx
- src/common/Destinations.tsx
- src/service/FakeDB.ts
- src/service/Model.ts
> Issue-64: Create three different user categories

- .github/workflows/publish.yaml
- src/App.tsx
- src/Behavior.tsx
- src/Consumers.tsx
- src/Home.tsx
- src/Routes.tsx
- src/User.tsx
- src/common/ConsumerTools.tsx
- src/common/DefaultAppBar.tsx
- src/common/DefaultBottomNavigation.tsx
- src/common/Destinations.tsx
- src/consumers/ConsumerCard.tsx
- src/index.tsx
- src/service/Executor.ts
- src/service/FakeBackend.ts
- src/service/FakeDB.ts
- src/thermostats/ThermostatDaySetting.tsx
fixes #66 
fixes #74 
fixes #75
> Issue-66: Hide thermostats for students

- src/Mood.tsx
- src/Routes.tsx
- src/service/BackendService.ts
- src/service/FakeBackend.ts
- src/service/FakeDB.ts
- src/service/Model.ts
> Issue-78: Improve mood component

- src/App.tsx
- src/service/BackendService.ts
- src/service/FakeBackend.ts
> Issue-83: Send tracking to backend

- src/App.tsx
- src/Behavior.tsx
- src/Consumers.tsx
- src/Mood.tsx
- src/Thermostats.tsx
- src/User.tsx
- src/common/InfoDialog.tsx
- src/common/ResponsiveIconButton.tsx
- src/locales/de/translation.json
- src/locales/en/translation.json
Fixes #91 
Fixes #92 
Fixes #93
> Issue-91: Add help buttons

- src/Archive.tsx
- src/Behavior.tsx
- src/Consumers.tsx
- src/Home.tsx
- src/Mood.tsx
- src/Power.tsx
- src/Thermostats.tsx
- src/Upload.tsx
- src/User.tsx
- src/common/DefaultAppBar.tsx
> Issue-98: Make nav bar permanent for desktop

- src/App.tsx
- src/Archive.tsx
- src/Behavior.tsx
- src/Consumers.tsx
- src/Home.tsx
- src/Mood.tsx
- src/Page404.tsx
- src/Power.tsx
- src/Routes.tsx
- src/Thermostats.tsx
- src/Upload.tsx
- src/User.tsx
- src/behavior/BehaviorDragSelect.tsx
- src/common/DefaultAppBar.tsx
- src/common/DefaultBottomNavigation.tsx
- src/common/InfoDialog.tsx
- src/common/ResponsiveIconButton.tsx
- src/consumers/ConsumerCard.tsx
- src/service/Executor.ts
- src/service/FakeBackend.ts
> Issue-100: Restructure app, move app bar on outer layer

- src/App.tsx
- src/Behavior.tsx
- src/Mood.tsx
- src/Thermostats.tsx
- src/common/AlertSnackbar.tsx
- src/common/ResponsiveIconButton.tsx
- src/locales/de/translation.json
- src/locales/en/translation.json
- src/thermostats/ModifyTimeItemDialog.tsx
- src/thermostats/ThermostatDaySetting.tsx
> Issue-111: Translate thermostats page

- src/Archive.tsx
- src/PastBehavior.tsx
- src/Routes.tsx
- src/archive/ArchiveEntry.tsx
- src/behavior/BehaviorDragSelect.tsx
> Issue-95: Add behavior site to archive

- src/Upload.tsx
> Issue-89: Add links to network operators

- src/Archive.tsx
- src/Behavior.tsx
- src/Consumers.tsx
- src/Mood.tsx
- src/PastBehavior.tsx
- src/Upload.tsx
- src/User.tsx
- src/locales/de/translation.json
- src/locales/en/translation.json
> Issue-127: Insert info texts

- package-lock.json
- package.json
- src/Feedback.tsx
- src/Home.tsx
> Issue-71: Create predictions pie chart

- src/Behavior.tsx
- src/PastBehavior.tsx
- src/Upload.tsx
- src/behavior/BehaviorDragSelect.tsx
> Issue-164: Remove unecessary network operators

- src/App.tsx
- src/Archive.tsx
- src/Behavior.tsx
- src/Consumers.tsx
- src/Feedback.tsx
- src/Home.tsx
- src/PastBehavior.tsx
- src/Upload.tsx
- src/User.tsx
- src/WellBeing.tsx
- src/common/DefaultAppBar.tsx
> Fix: Disable back button

- src/Feedback.tsx
- src/feedback/Charts.ts
- src/service/FakeBackend.ts
> Issue-178: Change feedback bar color
